#!/usr/bin/env python3
"""Bake docs/blog/articles into theme Liquid so Journal always has its content.

Source of truth: docs/blog/articles/*.html + index.json (same copy as preview/blog).
Re-run after editing those files. Does not touch checkout.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTICLES_DIR = ROOT / "docs" / "blog" / "articles"
SNIPPETS = ROOT / "valtora-theme" / "snippets"
BODY_OUT = SNIPPETS / "journal-article-body.liquid"
CARDS_OUT = SNIPPETS / "journal-baked-index.liquid"

PUBLISHED_SHORT = "12 Aug 2026"
PUBLISHED_LONG = "12 August 2026"
PUBLISHED_ISO = "2026-08-12"
AUTHOR_LINE = "Ben Acolatse, CEO"


def liquid_string(value: str) -> str:
    return value.replace("'", "\\'")


def load_catalog() -> list[dict]:
    return json.loads((ARTICLES_DIR / "index.json").read_text(encoding="utf-8"))


def liquid_safe(html: str) -> str:
    if "{%" in html or "{{" in html:
        raise SystemExit("article HTML contains Liquid markers; escape before baking")
    return html.rstrip() + "\n"


def build_body_snippet(catalog: list[dict]) -> str:
    lines = [
        "{%- comment -%}",
        "  Baked Journal article bodies. Generated by scripts/bake-journal-articles.py",
        "  from docs/blog/articles. Do not delete — Journal content is part of the storefront.",
        "  Input: article_handle",
        "{%- endcomment -%}",
        "{%- case article_handle -%}",
    ]
    for item in catalog:
        handle = item["handle"]
        html_path = ARTICLES_DIR / f"{handle}.html"
        html = liquid_safe(html_path.read_text(encoding="utf-8"))
        lines.append(f"  {{%- when '{handle}' -%}}")
        for html_line in html.splitlines():
            lines.append(f"    {html_line}" if html_line else "")
    lines.append("  {%- else -%}")
    lines.append("    <p>This Journal note is not in the theme yet.</p>")
    lines.append("{%- endcase -%}")
    lines.append("")
    return "\n".join(lines)


def build_cards_snippet(catalog: list[dict]) -> str:
    lines = [
        "{%- comment -%}",
        "  Baked Journal index (cards + in-page article panels).",
        "  Generated by scripts/bake-journal-articles.py. Do not delete.",
        "  Published Shopify blog posts win when present; baked notes fill the rest.",
        "{%- endcomment -%}",
        "{%- liquid",
        "  assign journal_blog = blogs['journal']",
        "  assign journal_count = journal_blog.articles_count | default: 0 | plus: 0",
        "  assign published = ','",
        "  if journal_count > 0",
        "    for article in journal_blog.articles",
        "      assign published = published | append: article.handle | append: ','",
        "    endfor",
        "  endif",
        "-%}",
        "",
        '<div class="journal-with-panels">',
        '  <div class="journal-index-view" id="journal-index">',
        '    <ul class="blog-index__grid" role="list">',
        "      {%- if journal_count > 0 -%}",
        "        {%- for article in journal_blog.articles limit: 12 -%}",
        '          <li class="blog-card" data-reveal-child style="--reveal-delay: {{ forloop.index0 | times: 50 }}ms">',
        '            <a class="blog-card__link" href="{{ article.url }}">',
        "              {%- if article.image -%}",
        '                <div class="blog-card__media">',
        "                  {{ article.image | image_url: width: 1200 | image_tag: loading: 'lazy', widths: '400,800,1200', sizes: '(min-width: 1100px) 30vw, 90vw', alt: article.image.alt | default: article.title }}",
        "                </div>",
        "              {%- else -%}",
        '                <div class="blog-card__media blog-card__media--empty" aria-hidden="true"></div>',
        "              {%- endif -%}",
        '              <div class="blog-card__body">',
        "                {%- if article.tags.size > 0 -%}",
        '                  <p class="blog-card__tag">{{ article.tags.first }}</p>',
        "                {%- endif -%}",
        '                <h2 class="blog-card__title">{{ article.title }}</h2>',
        "                {%- if article.excerpt != blank -%}",
        '                  <p class="blog-card__excerpt">{{ article.excerpt | strip_html | truncate: 160 }}</p>',
                "                {%- else -%}",
        '                  <p class="blog-card__excerpt">{{ article.content | strip_html | truncate: 160 }}</p>',
        "                {%- endif -%}",
        '                <p class="blog-card__meta">',
        "                  <time datetime=\"{{ article.published_at | date: '%Y-%m-%d' }}\">{{ article.published_at | date: '%-d %b %Y' }}</time>",
        f'                  <span aria-hidden="true"> · </span><span>{AUTHOR_LINE}</span>',
        "                </p>",
        "              </div>",
        "            </a>",
        "          </li>",
        "        {%- endfor -%}",
        "      {%- endif -%}",
    ]
    for i, item in enumerate(catalog):
        handle = item["handle"]
        title = item["title"]
        excerpt = item["excerpt"]
        tag = item["tags"][0]
        delay = i * 50
        lines.extend(
            [
                f"      {{%- unless published contains ',{handle},' -%}}",
                f'        <li class="blog-card" data-reveal-child style="--reveal-delay: {delay}ms">',
                f'          <a class="blog-card__link" href="{{% render \'journal-article-href\', article_handle: \'{handle}\' %}}">',
                '            <div class="blog-card__media blog-card__media--empty" aria-hidden="true"></div>',
                '            <div class="blog-card__body">',
                f'              <p class="blog-card__tag">{tag}</p>',
                f'              <h2 class="blog-card__title">{title}</h2>',
                f'              <p class="blog-card__excerpt">{excerpt}</p>',
                '              <p class="blog-card__meta">',
                f'                <time datetime="{PUBLISHED_ISO}">{PUBLISHED_SHORT}</time>',
                f'                <span aria-hidden="true"> · </span><span>{AUTHOR_LINE}</span>',
                "              </p>",
                "            </div>",
                "          </a>",
                "        </li>",
                "      {%- endunless -%}",
            ]
        )
    lines.extend(
        [
            "    </ul>",
            "  </div>",
            "",
        ]
    )
    for item in catalog:
        handle = item["handle"]
        lines.extend(
            [
                f'  {{%- unless published contains \',{handle},\' -%}}',
                f'    <article class="journal-article-panel section article" id="{handle}" itemscope itemtype="https://schema.org/Article">',
                "      {% render 'journal-article-layout', article_handle: '" + handle + "' %}",
                "    </article>",
                "  {%- endunless -%}",
            ]
        )
    lines.extend(["</div>", ""])
    return "\n".join(lines)


def main() -> None:
    catalog = load_catalog()
    missing = [item["handle"] for item in catalog if not (ARTICLES_DIR / f"{item['handle']}.html").exists()]
    if missing:
        raise SystemExit(f"missing article HTML: {missing}")
    SNIPPETS.mkdir(parents=True, exist_ok=True)
    BODY_OUT.write_text(build_body_snippet(catalog), encoding="utf-8")
    CARDS_OUT.write_text(build_cards_snippet(catalog), encoding="utf-8")
    print(f"wrote {BODY_OUT.relative_to(ROOT)} ({len(catalog)} articles)")
    print(f"wrote {CARDS_OUT.relative_to(ROOT)}")
    print(f"published date in cards: {PUBLISHED_SHORT} ({PUBLISHED_ISO})")


if __name__ == "__main__":
    main()
